package:
  name: external-node # this name?
  version: 27.4.0
  epoch: 0
  description: ZKsync External Node is a read-replica of the main (centralized) node that can be run by anyone.
  copyright:
    - license: Apache-2.0
    - license: MIT

environment:
  contents:
    packages:
      - gcc
      - curl
      - clang
      - glibc-dev
      - openssl-dev
      - liburing-dev
  environment:
    # Allow unstable features with stable rust
    RUSTC_BOOTSTRAP: 1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/matter-labs/zksync-era
      tag: core-v${{package.version}}
      expected-commit: f9bf60a05366cee82213bed03daea2580c8de4cc
      destination: zksync

subpackages:
  # only builds on rust nightly
  - name: ${{package.name}}-external-node
    description: External Node is a read replica that can sync from the main node and serve the state locally.
    pipeline:
      - name: Configure and Build
        working-directory: ${{package.srcdir}}/zksync/core/bin/external_node
        uses: cargo/build
        with:
          output: external-node
      - uses: strip
    dependencies:
      provides:
        - ${{package.name}}-external-node=${{package.full-version}}
    # how do I test this?
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-block-reverter
    description:
    pipeline:
      - name: Configure and Build
        working-directory: ${{package.srcdir}}/zksync/core/bin/block_reverter
        uses: cargo/build
        with:
          output: block-reverter
      - uses: strip
    dependencies:
      provides:
        - ${{package.name}}-block-reverter=${{package.full-version}}
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for using External Node in OCI containers
    dependencies:
      runtime:
        - busybox
      provides:
        - ${{package.name}}-oci-entrypoint=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/lib/external-node/init
          cp ${{package.srcdir}}/zksync/docker/external-node/entrypoint.sh ${{targets.subpkgdir}}/var/lib/external-node/init/entrypoint.sh
          chmod +x ${{targets.subpkgdir}}/var/lib/external-node/init/entrypoint.sh

update:
  enabled: true
  github:
    identifier: matter-labs/zksync-era
    strip-prefix: core-v
    use-tag: true
