package:
  name: fleet
  version: 0.12.2
  epoch: 0
  description: Deploy workloads from Git to large fleets of Kubernetes clusters
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/fleet
      tag: v${{package.version}}
      expected-commit: fcb09948fb937f043ab421b2b7ef03d7cbcce02b

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/net@v0.38.0
        helm.sh/helm/v3@v3.17.3
        k8s.io/kubernetes@v1.32.4

  - uses: go/build
    with:
      packages: ./cmd/fleetcontroller
      output: fleetcontroller

  - uses: strip

subpackages:
  - name: fleet-termination-log
    description: fleet-termination-log outputs fleet's termination log to /dev/termination-log
    dependencies:
      runtime:
        - busybox
      provides:
        - fleet-termination-log=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/lib/fleet
          cp package/log.sh ${{targets.subpkgdir}}/var/lib/fleet/log.sh
          chmod +x ${{targets.subpkgdir}}/var/lib/fleet/log.sh

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - runs: |
        fleetcontroller --version
        fleetcontroller --help
    - name: "Setup KWOK cluster"
      uses: test/kwok/cluster
    - name: "Install CRDs"
      runs: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/fleet/refs/tags/v${{package.version}}/charts/fleet-crd/templates/crds.yaml
        kubectl wait --for=condition=Established crd --all --timeout=60s
        kubectl create ns cattle-fleet-system
    - name: "Start fleet controller daemon"
      uses: test/daemon-check-output
      with:
        start: |
          fleetcontroller \
            --namespace cattle-fleet-system  \
            --kubeconfig ~/.kube/config
        timeout: 30
        expected_output: |
          listening for changes on local cluster
          starting job scheduler
          starting manager
          successfully acquired lease
        post: |
          # Check metrics endpoint
          curl -sk http://localhost:8080/metrics

update:
  enabled: true
  github:
    identifier: rancher/fleet
    strip-prefix: v
