package:
  name: tinydir
  version: 1.2.6
  epoch: 1
  description: "Lightweight, portable C library that simplifies interaction with directories and files in a filesystem"
  copyright:
    - license: "BSD-2-Clause"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cxong/tinydir.git
      tag: ${{package.version}}
      expected-commit: 6ba79293a5e4ea015343e20453b4f4595c644515

  - runs: mkdir -p ${{targets.destdir}}/usr/include

  - runs: cp tinydir.h ${{targets.destdir}}/usr/include/

  - uses: strip

test:
  environment:
    contents:
      packages:
        - cmake
        - gcc
        - make
        - shadow
        - sudo-rs
        - glibc-locales
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/cxong/tinydir.git
        tag: ${{package.version}}
        expected-commit: 6ba79293a5e4ea015343e20453b4f4595c644515
    - name: "run upstream tests"
      runs: |
        # Based on upstream workflow: https://github.com/cxong/tinydir/blob/master/.github/workflows/cmake.yml
        # remove the local copy of tinydir.h
        rm tinydir.h
        # build
        cmake -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON tests
        cmake --build ./build --config Release
        # test
        cd build
        ctest -C Release

update:
  enabled: true
  github:
    identifier: cxong/tinydir
